/* eslint-disable no-unused-expressions */
[
  {
    status: 'OK',
    copyright: 'Copyright (c) 2019 Pro Publica Inc. All Rights Reserved.',
    results: [
      {
        member_id: 'F000062',
        first_name: 'Dianne',
        middle_name: null,
        last_name: 'Feinstein',
        suffix: null,
        date_of_birth: '1933-06-22',
        gender: 'F',
        url: 'https://www.feinstein.senate.gov',
        times_topics_url:
          'http://topics.nytimes.com/top/reference/timestopics/people/f/dianne_feinstein/index.html',
        times_tag: 'Feinstein, Dianne (Per)',
        govtrack_id: '300043',
        cspan_id: '13061',
        votesmart_id: '53273',
        icpsr_id: '49300',
        twitter_account: 'SenFeinstein',
        facebook_account: 'senatorfeinstein',
        youtube_account: 'SenatorFeinstein',
        crp_id: 'N00007364',
        google_entity_id: '/m/01gqws',
        rss_url: 'https://www.feinstein.senate.gov/public/?a=rss.feed',
        in_office: true,
        current_party: 'D',
        most_recent_vote: '2019-08-01',
        last_updated: '2019-08-13 07:35:30 -0400',
        roles: [
          {
            congress: '116',
            chamber: 'Senate',
            title: 'Senator, 1st Class',
            short_title: 'Sen.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: 'S0CA00199',
            seniority: '27',
            senate_class: '1',
            state_rank: 'senior',
            lis_id: 'S221',
            ocd_id: 'ocd-division/country:us/state:ca',
            start_date: '2019-01-03',
            end_date: '2021-01-03',
            office: '331 Hart Senate Office Building',
            phone: '202-224-3841',
            fax: null,
            contact_form:
              'https://www.feinstein.senate.gov/public/index.cfm/e-mail-me',
            bills_sponsored: 43,
            bills_cosponsored: 316,
            missed_votes_pct: 0,
            votes_with_party_pct: 91.6,
            committees: [
              {
                name: 'Committee on the Judiciary',
                code: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SSJU.json',
                side: 'minority',
                title: 'Ranking Member',
                rank_in_party: 1,
                begin_date: '2019-01-09',
                end_date: '2021-01-03',
              },
              {
                name: 'Committee on Rules and Administration',
                code: 'SSRA',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SSRA.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 2,
                begin_date: '2019-01-09',
                end_date: '2021-01-03',
              },
              {
                name: 'Select Committee on Intelligence',
                code: 'SLIN',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SLIN.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 2,
                begin_date: '2019-01-09',
                end_date: '2021-01-03',
              },
              {
                name: 'Committee on Appropriations',
                code: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SSAP.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 3,
                begin_date: '2019-01-09',
                end_date: '2021-01-03',
              },
              {
                name: 'United States Caucus on International Narcotics Control',
                code: 'SCNC',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SCNC.json',
                side: 'minority',
                title: 'Ranking Member',
                rank_in_party: 1,
                begin_date: '',
                end_date: '2021-01-03',
              },
            ],
            subcommittees: [
              {
                name:
                  'Agriculture, Rural Development, Food and Drug Administration, and Related Agencies',
                code: 'SSAP01',
                parent_committee_id: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SSAP/subcommittees/SSAP01.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 2,
                begin_date: '',
                end_date: '2021-01-03',
              },
              {
                name: 'Department of Defense Subcommittee',
                code: 'SSAP02',
                parent_committee_id: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SSAP/subcommittees/SSAP02.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 3,
                begin_date: '',
                end_date: '2021-01-03',
              },
              {
                name: 'Border Security and Immigration Subcommittee',
                code: 'SSJU04',
                parent_committee_id: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SSJU/subcommittees/SSJU04.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 2,
                begin_date: '',
                end_date: '2021-01-03',
              },
              {
                name:
                  'Commerce, Justice, Science, and Related Agencies Subcommittee',
                code: 'SSAP16',
                parent_committee_id: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SSAP/subcommittees/SSAP16.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 3,
                begin_date: '',
                end_date: '2021-01-03',
              },
              {
                name: 'Crime and Terrorism',
                code: 'SSJU22',
                parent_committee_id: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SSJU/subcommittees/SSJU22.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 2,
                begin_date: '',
                end_date: '2021-01-03',
              },
              {
                name:
                  'Department of the Interior, Environment, and Related Agencies',
                code: 'SSAP17',
                parent_committee_id: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SSAP/subcommittees/SSAP17.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 2,
                begin_date: '',
                end_date: '2021-01-03',
              },
              {
                name: 'Energy and Water Development',
                code: 'SSAP22',
                parent_committee_id: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SSAP/subcommittees/SSAP22.json',
                side: 'minority',
                title: 'Ranking Member',
                rank_in_party: 1,
                begin_date: '',
                end_date: '2021-01-03',
              },
              {
                name:
                  'Transportation, Housing and Urban Development, and Related Agencies',
                code: 'SSAP24',
                parent_committee_id: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SSAP/subcommittees/SSAP24.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 4,
                begin_date: '',
                end_date: '2021-01-03',
              },
            ],
          },
          {
            congress: '115',
            chamber: 'Senate',
            title: 'Senator, 1st Class',
            short_title: 'Sen.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: 'S0CA00199',
            seniority: '25',
            senate_class: '1',
            state_rank: 'senior',
            lis_id: 'S221',
            ocd_id: 'ocd-division/country:us/state:ca',
            start_date: '2017-01-03',
            end_date: '2019-01-03',
            office: '331 Hart Senate Office Building',
            phone: '202-224-3841',
            fax: '202-228-3954',
            contact_form:
              'https://www.feinstein.senate.gov/public/index.cfm/e-mail-me',
            bills_sponsored: 67,
            bills_cosponsored: 490,
            missed_votes_pct: 6.18,
            votes_with_party_pct: 91.46,
            committees: [
              {
                name: 'United States Caucus on International Narcotics Control',
                code: 'SCNC',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SCNC.json',
                side: 'minority',
                title: 'Ranking Member',
                rank_in_party: 1,
                begin_date: '2017-01-03',
                end_date: '2019-01-03',
              },
              {
                name: 'Select Committee on Intelligence',
                code: 'SLIN',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SLIN.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 2,
                begin_date: '2017-01-03',
                end_date: '2019-01-03',
              },
              {
                name: 'Committee on Appropriations',
                code: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSAP.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 3,
                begin_date: '2017-01-03',
                end_date: '2019-01-03',
              },
              {
                name: 'Committee on the Judiciary',
                code: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSJU.json',
                side: 'minority',
                title: 'Ranking Member',
                rank_in_party: 1,
                begin_date: '2017-01-03',
                end_date: '2019-01-03',
              },
              {
                name: 'Committee on Rules and Administration',
                code: 'SSRA',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSRA.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 2,
                begin_date: '2017-01-03',
                end_date: '2019-01-03',
              },
            ],
            subcommittees: [
              {
                name: 'Border Security and Immigration Subcommittee',
                code: 'SSJU04',
                parent_committee_id: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSJU/subcommittees/SSJU04.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 2,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name: 'Crime and Terrorism',
                code: 'SSJU22',
                parent_committee_id: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSJU/subcommittees/SSJU22.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 2,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name:
                  'Agriculture, Rural Development, Food and Drug Administration, and Related Agencies',
                code: 'SSAP01',
                parent_committee_id: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSAP/subcommittees/SSAP01.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 2,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name:
                  'Commerce, Justice, Science, and Related Agencies Subcommittee',
                code: 'SSAP16',
                parent_committee_id: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSAP/subcommittees/SSAP16.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 3,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name: 'Department of Defense Subcommittee',
                code: 'SSAP02',
                parent_committee_id: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSAP/subcommittees/SSAP02.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 3,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name:
                  'Department of the Interior, Environment, and Related Agencies',
                code: 'SSAP17',
                parent_committee_id: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSAP/subcommittees/SSAP17.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 2,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name: 'Energy and Water Development',
                code: 'SSAP22',
                parent_committee_id: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSAP/subcommittees/SSAP22.json',
                side: 'minority',
                title: 'Ranking Member',
                rank_in_party: 1,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name:
                  'Transportation, Housing and Urban Development, and Related Agencies',
                code: 'SSAP24',
                parent_committee_id: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSAP/subcommittees/SSAP24.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 4,
                begin_date: '',
                end_date: '2019-01-03',
              },
            ],
          },
          {
            congress: '114',
            chamber: 'Senate',
            title: 'Senator, 1st Class',
            short_title: 'Sen.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: 'S0CA00199',
            seniority: '23',
            senate_class: '1',
            state_rank: '',
            lis_id: 'S221',
            ocd_id: 'ocd-division/country:us/state:ca',
            start_date: '2015-01-06',
            end_date: '2017-01-03',
            office: null,
            phone: null,
            fax: null,
            contact_form: null,
            bills_sponsored: 67,
            bills_cosponsored: 285,
            missed_votes_pct: 2.59,
            votes_with_party_pct: 92.43,
            committees: [
              {
                name: 'United States Caucus on International Narcotics Control',
                code: 'SCNC',
                api_uri:
                  'https://api.propublica.org/congress/v1/114/senate/committees/SCNC.json',
                rank_in_party: null,
                begin_date: '',
                end_date: '2017-01-03',
              },
              {
                name: 'Committee on Appropriations',
                code: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/114/senate/committees/SSAP.json',
                rank_in_party: null,
                begin_date: '',
                end_date: '2017-01-03',
              },
              {
                name: 'Committee on Rules and Administration',
                code: 'SSRA',
                api_uri:
                  'https://api.propublica.org/congress/v1/114/senate/committees/SSRA.json',
                rank_in_party: null,
                begin_date: '',
                end_date: '2017-01-03',
              },
              {
                name: 'Committee on the Judiciary',
                code: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/114/senate/committees/SSJU.json',
                rank_in_party: null,
                begin_date: '',
                end_date: '2017-01-03',
              },
              {
                name: 'Select Committee on Intelligence',
                code: 'SLIN',
                api_uri:
                  'https://api.propublica.org/congress/v1/114/senate/committees/SLIN.json',
                rank_in_party: null,
                begin_date: '',
                end_date: '2017-01-03',
              },
            ],
            subcommittees: [],
          },
          {
            congress: '113',
            chamber: 'Senate',
            title: 'Senator, 1st Class',
            short_title: 'Sen.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: '',
            seniority: '21',
            senate_class: '1',
            state_rank: '',
            lis_id: 'S221',
            ocd_id: 'ocd-division/country:us/state:ca',
            start_date: '2013-01-03',
            end_date: '2015-01-02',
            office: null,
            phone: null,
            fax: null,
            contact_form: null,
            bills_sponsored: 69,
            bills_cosponsored: 269,
            missed_votes_pct: 4.57,
            votes_with_party_pct: 98.72,
            committees: [
              {
                name: 'Committee on Rules and Administration',
                code: 'SSRA',
                api_uri:
                  'https://api.propublica.org/congress/v1/113/senate/committees/SSRA.json',
                rank_in_party: 2,
                begin_date: '2013-01-03',
                end_date: '2015-01-03',
              },
              {
                name: 'Committee on the Judiciary',
                code: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/113/senate/committees/SSJU.json',
                rank_in_party: 2,
                begin_date: '2013-01-03',
                end_date: '2015-01-03',
              },
              {
                name: 'Select Committee on Intelligence',
                code: 'SLIN',
                api_uri:
                  'https://api.propublica.org/congress/v1/113/senate/committees/SLIN.json',
                rank_in_party: 1,
                begin_date: '2013-01-03',
                end_date: '2015-01-03',
              },
              {
                name: 'Committee on Appropriations',
                code: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/113/senate/committees/SSAP.json',
                rank_in_party: 5,
                begin_date: '2013-01-03',
                end_date: '2015-01-03',
              },
            ],
            subcommittees: [
              {
                name:
                  'Agriculture, Rural Development, Food and Drug Administration, and Related Agencies',
                code: 'SSAP01',
                parent_committee_id: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/113/senate/committees/SSAP/subcommittees/SSAP01.json',
                rank_in_party: 2,
                begin_date: '2013-01-03',
                end_date: '2015-01-03',
              },
              {
                name:
                  'Commerce, Justice, Science, and Related Agencies Subcommittee',
                code: 'SSAP16',
                parent_committee_id: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/113/senate/committees/SSAP/subcommittees/SSAP16.json',
                rank_in_party: 3,
                begin_date: '2013-01-03',
                end_date: '2015-01-03',
              },
              {
                name: 'Department of Defense Subcommittee',
                code: 'SSAP02',
                parent_committee_id: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/113/senate/committees/SSAP/subcommittees/SSAP02.json',
                rank_in_party: 4,
                begin_date: '2013-01-03',
                end_date: '2015-01-03',
              },
              {
                name:
                  'Department of the Interior, Environment, and Related Agencies',
                code: 'SSAP17',
                parent_committee_id: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/113/senate/committees/SSAP/subcommittees/SSAP17.json',
                rank_in_party: 2,
                begin_date: '2013-01-03',
                end_date: '2015-01-03',
              },
              {
                name: 'Energy and Water Development',
                code: 'SSAP22',
                parent_committee_id: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/113/senate/committees/SSAP/subcommittees/SSAP22.json',
                rank_in_party: 1,
                begin_date: '2013-01-03',
                end_date: '2015-01-03',
              },
              {
                name: 'Crime and Terrorism',
                code: 'SSJU22',
                parent_committee_id: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/113/senate/committees/SSJU/subcommittees/SSJU22.json',
                rank_in_party: 2,
                begin_date: '2013-01-03',
                end_date: '2015-01-03',
              },
              {
                name: 'Border Security and Immigration Subcommittee',
                code: 'SSJU04',
                parent_committee_id: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/113/senate/committees/SSJU/subcommittees/SSJU04.json',
                rank_in_party: 3,
                begin_date: '2013-01-03',
                end_date: '2015-01-03',
              },
              {
                name:
                  'Transportation, Housing and Urban Development, and Related Agencies',
                code: 'SSAP24',
                parent_committee_id: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/113/senate/committees/SSAP/subcommittees/SSAP24.json',
                rank_in_party: 6,
                begin_date: '2013-01-03',
                end_date: '2015-01-03',
              },
            ],
          },
          {
            congress: '112',
            chamber: 'Senate',
            title: 'Senator, 1st Class',
            short_title: 'Sen.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: '',
            seniority: '19',
            senate_class: '1',
            state_rank: '',
            lis_id: 'S221',
            ocd_id: 'ocd-division/country:us/state:ca',
            start_date: '2011-01-04',
            end_date: '2013-01-03',
            office: null,
            phone: null,
            fax: null,
            contact_form: null,
            bills_sponsored: 113,
            bills_cosponsored: 298,
            missed_votes_pct: 1.85,
            votes_with_party_pct: 95.39,
            committees: [
              {
                name: 'Select Committee on Intelligence',
                code: 'SLIN',
                api_uri:
                  'https://api.propublica.org/congress/v1/112/senate/committees/SLIN.json',
                rank_in_party: 1,
                begin_date: '2011-01-05',
                end_date: '2013-01-03',
              },
              {
                name: 'Committee on Appropriations',
                code: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/112/senate/committees/SSAP.json',
                rank_in_party: 7,
                begin_date: '2011-01-05',
                end_date: '2013-01-03',
              },
              {
                name: 'Committee on the Judiciary',
                code: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/112/senate/committees/SSJU.json',
                rank_in_party: 3,
                begin_date: '2011-01-05',
                end_date: '2013-01-03',
              },
              {
                name: 'Committee on Rules and Administration',
                code: 'SSRA',
                api_uri:
                  'https://api.propublica.org/congress/v1/112/senate/committees/SSRA.json',
                rank_in_party: 3,
                begin_date: '2011-01-05',
                end_date: '2013-01-03',
              },
            ],
            subcommittees: [],
          },
          {
            congress: '111',
            chamber: 'Senate',
            title: 'Senator, 1st Class',
            short_title: 'Sen.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: '',
            seniority: '17',
            senate_class: '1',
            state_rank: '',
            lis_id: 'S221',
            ocd_id: 'ocd-division/country:us/state:ca',
            start_date: '2009-01-06',
            end_date: '2011-01-03',
            office: null,
            phone: null,
            fax: null,
            contact_form: null,
            bills_sponsored: 138,
            bills_cosponsored: 281,
            missed_votes_pct: 0.3,
            votes_with_party_pct: 96.3,
            committees: [
              {
                name: 'Select Committee on Intelligence',
                code: 'SLIN',
                api_uri:
                  'https://api.propublica.org/congress/v1/111/senate/committees/SLIN.json',
                rank_in_party: 1,
                begin_date: '2009-01-21',
                end_date: '2011-01-03',
              },
              {
                name: 'Committee on Appropriations',
                code: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/111/senate/committees/SSAP.json',
                rank_in_party: 8,
                begin_date: '2009-01-21',
                end_date: '2011-01-03',
              },
              {
                name: 'Committee on the Judiciary',
                code: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/111/senate/committees/SSJU.json',
                rank_in_party: 3,
                begin_date: '2009-01-21',
                end_date: '2011-01-03',
              },
              {
                name: 'Committee on Rules and Administration',
                code: 'SSRA',
                api_uri:
                  'https://api.propublica.org/congress/v1/111/senate/committees/SSRA.json',
                rank_in_party: 4,
                begin_date: '2009-01-21',
                end_date: '2011-01-03',
              },
            ],
            subcommittees: [],
          },
          {
            congress: '110',
            chamber: 'Senate',
            title: 'Senator, 1st Class',
            short_title: 'Sen.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: '',
            seniority: '15',
            senate_class: '1',
            state_rank: '',
            lis_id: 'S221',
            ocd_id: 'ocd-division/country:us/state:ca',
            start_date: '2007-01-04',
            end_date: '2009-01-03',
            office: null,
            phone: null,
            fax: null,
            contact_form: null,
            bills_sponsored: 138,
            bills_cosponsored: 380,
            missed_votes_pct: 2.74,
            votes_with_party_pct: 93.74,
            committees: [
              {
                name: 'Joint Committee on the Library',
                code: 'JSLC',
                api_uri:
                  'https://api.propublica.org/congress/v1/110/senate/committees/JSLC.json',
                rank_in_party: 1,
                begin_date: '2007-03-26',
                end_date: '2009-01-03',
              },
              {
                name: 'Joint Committee on Printing',
                code: 'JSPR',
                api_uri:
                  'https://api.propublica.org/congress/v1/110/senate/committees/JSPR.json',
                rank_in_party: 1,
                begin_date: '2007-03-26',
                end_date: '2009-01-03',
              },
              {
                name: 'Committee on Appropriations',
                code: 'SSAP',
                api_uri:
                  'https://api.propublica.org/congress/v1/110/senate/committees/SSAP.json',
                rank_in_party: 9,
                begin_date: '2007-01-12',
                end_date: '2009-01-03',
              },
              {
                name: 'Committee on the Judiciary',
                code: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/110/senate/committees/SSJU.json',
                rank_in_party: 5,
                begin_date: '2007-01-12',
                end_date: '2009-01-03',
              },
              {
                name: 'Committee on Rules and Administration',
                code: 'SSRA',
                api_uri:
                  'https://api.propublica.org/congress/v1/110/senate/committees/SSRA.json',
                rank_in_party: 4,
                begin_date: '2007-01-12',
                end_date: '2009-01-03',
              },
              {
                name: 'Select Committee on Intelligence',
                code: 'SLIN',
                api_uri:
                  'https://api.propublica.org/congress/v1/110/senate/committees/SLIN.json',
                rank_in_party: 2,
                begin_date: '2007-01-12',
                end_date: '2009-01-03',
              },
            ],
            subcommittees: [],
          },
          {
            congress: '109',
            chamber: 'Senate',
            title: 'Senator, 1st Class',
            short_title: 'Sen.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: '',
            seniority: '13',
            senate_class: '1',
            state_rank: '',
            lis_id: 'S221',
            ocd_id: 'ocd-division/country:us/state:ca',
            start_date: '2005-01-04',
            end_date: '2007-01-03',
            office: null,
            phone: null,
            fax: null,
            contact_form: null,
            bills_sponsored: 129,
            bills_cosponsored: 337,
            missed_votes_pct: 1.71,
            votes_with_party_pct: 92.11,
            committees: [],
            subcommittees: [],
          },
          {
            congress: '108',
            chamber: 'Senate',
            title: 'Senator, 1st Class',
            short_title: 'Sen.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: '',
            seniority: '11',
            senate_class: '1',
            state_rank: '',
            lis_id: 'S221',
            ocd_id: 'ocd-division/country:us/state:ca',
            start_date: '2003-01-07',
            end_date: '2005-01-03',
            office: null,
            phone: null,
            fax: null,
            contact_form: null,
            bills_sponsored: 69,
            bills_cosponsored: 318,
            missed_votes_pct: 1.63,
            votes_with_party_pct: 90.81,
            committees: [],
            subcommittees: [],
          },
          {
            congress: '107',
            chamber: 'Senate',
            title: 'Senator, 1st Class',
            short_title: 'Sen.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: '',
            seniority: '9',
            senate_class: '1',
            state_rank: '',
            lis_id: 'S221',
            ocd_id: 'ocd-division/country:us/state:ca',
            start_date: '2001-01-03',
            end_date: '2003-01-03',
            office: null,
            phone: null,
            fax: null,
            contact_form: null,
            bills_sponsored: 112,
            bills_cosponsored: 269,
            missed_votes_pct: 1.42,
            votes_with_party_pct: 88.46,
            committees: [],
            subcommittees: [],
          },
          {
            congress: '106',
            chamber: 'Senate',
            title: 'Senator, 1st Class',
            short_title: 'Sen.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: '',
            seniority: '7',
            senate_class: '1',
            state_rank: '',
            lis_id: 'S221',
            ocd_id: 'ocd-division/country:us/state:ca',
            start_date: '1999-01-06',
            end_date: '2001-01-03',
            office: null,
            phone: null,
            fax: null,
            contact_form: null,
            bills_sponsored: 79,
            bills_cosponsored: 375,
            missed_votes_pct: 7.14,
            votes_with_party_pct: 93.11,
            committees: [],
            subcommittees: [],
          },
          {
            congress: '105',
            chamber: 'Senate',
            title: 'Senator, 1st Class',
            short_title: 'Sen.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: '',
            seniority: '5',
            senate_class: '1',
            state_rank: '',
            lis_id: 'S221',
            ocd_id: 'ocd-division/country:us/state:ca',
            start_date: '1997-01-07',
            end_date: '1999-01-03',
            office: null,
            phone: null,
            fax: null,
            contact_form: null,
            bills_sponsored: 45,
            bills_cosponsored: 246,
            missed_votes_pct: 0.98,
            votes_with_party_pct: 89.6,
            committees: [],
            subcommittees: [],
          },
          {
            congress: '104',
            chamber: 'Senate',
            title: 'Senator, 1st Class',
            short_title: 'Sen.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: '',
            seniority: '3',
            senate_class: '1',
            state_rank: '',
            lis_id: 'S221',
            ocd_id: 'ocd-division/country:us/state:ca',
            start_date: '1995-01-04',
            end_date: '1997-01-03',
            office: null,
            phone: null,
            fax: null,
            contact_form: null,
            bills_sponsored: 25,
            bills_cosponsored: 163,
            missed_votes_pct: 0.66,
            votes_with_party_pct: 82.31,
            committees: [],
            subcommittees: [],
          },
          {
            congress: '103',
            chamber: 'Senate',
            title: 'Senator, 1st Class',
            short_title: 'Sen.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: '',
            seniority: '1',
            senate_class: '1',
            state_rank: '',
            lis_id: 'S221',
            ocd_id: 'ocd-division/country:us/state:ca',
            start_date: '1993-01-05',
            end_date: '1995-01-03',
            office: null,
            phone: null,
            fax: null,
            contact_form: null,
            bills_sponsored: 30,
            bills_cosponsored: 216,
            missed_votes_pct: 1.93,
            votes_with_party_pct: 88.34,
            committees: [],
            subcommittees: [],
          },
          {
            congress: '102',
            chamber: 'Senate',
            title: 'Senator, 1st Class',
            short_title: 'Sen.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: '',
            seniority: '1',
            senate_class: '1',
            state_rank: '',
            lis_id: 'S221',
            ocd_id: 'ocd-division/country:us/state:ca',
            start_date: '1992-11-10',
            end_date: '1993-01-03',
            office: null,
            phone: null,
            fax: null,
            contact_form: null,
            missed_votes_pct: 0,
            votes_with_party_pct: 0,
            committees: [],
            subcommittees: [],
          },
        ],
      },
    ],
  },
  {
    status: 'OK',
    copyright: 'Copyright (c) 2019 Pro Publica Inc. All Rights Reserved.',
    results: [
      {
        member_id: 'H001075',
        first_name: 'Kamala',
        middle_name: null,
        last_name: 'Harris',
        suffix: null,
        date_of_birth: '1964-10-20',
        gender: 'F',
        url: 'https://www.harris.senate.gov',
        times_topics_url: '',
        times_tag: '',
        govtrack_id: '412678',
        cspan_id: '1018696',
        votesmart_id: '120012',
        icpsr_id: '41701',
        twitter_account: 'SenKamalaHarris',
        facebook_account: 'SenatorKamalaHarris',
        youtube_account: null,
        crp_id: 'N00036915',
        google_entity_id: '/m/08sry2',
        rss_url: null,
        in_office: true,
        current_party: 'D',
        most_recent_vote: '2019-07-23',
        last_updated: '2019-08-13 07:35:33 -0400',
        roles: [
          {
            congress: '116',
            chamber: 'Senate',
            title: 'Senator, 3rd Class',
            short_title: 'Sen.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: 'S6CA00584',
            seniority: '1',
            senate_class: '3',
            state_rank: 'junior',
            lis_id: 'S387',
            ocd_id: 'ocd-division/country:us/state:ca',
            start_date: '2019-01-03',
            end_date: '2021-01-03',
            office: '112 Hart Senate Office Building',
            phone: '202-224-3553',
            fax: null,
            contact_form: 'https://www.harris.senate.gov/contact',
            bills_sponsored: 43,
            bills_cosponsored: 364,
            missed_votes_pct: 44.27,
            votes_with_party_pct: 70.55,
            committees: [
              {
                name: 'Committee on the Judiciary',
                code: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SSJU.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 10,
                begin_date: '2019-01-09',
                end_date: '2021-01-03',
              },
              {
                name: 'Select Committee on Intelligence',
                code: 'SLIN',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SLIN.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 6,
                begin_date: '2019-01-09',
                end_date: '2021-01-03',
              },
              {
                name: 'Committee on Homeland Security and Governmental Affairs',
                code: 'SSGA',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SSGA.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 4,
                begin_date: '2019-01-09',
                end_date: '2021-01-03',
              },
              {
                name: 'Committee on the Budget',
                code: 'SSBU',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SSBU.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 10,
                begin_date: '2019-01-09',
                end_date: '2021-01-03',
              },
            ],
            subcommittees: [
              {
                name: 'Permanent Subcommittee on Investigations',
                code: 'SSGA01',
                parent_committee_id: 'SSGA',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SSGA/subcommittees/SSGA01.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 3,
                begin_date: '2019-01-31',
                end_date: '2021-01-03',
              },
              {
                name: 'Federal Spending Oversight and Emergency Management',
                code: 'SSGA18',
                parent_committee_id: 'SSGA',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SSGA/subcommittees/SSGA18.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 2,
                begin_date: '2019-01-31',
                end_date: '2021-01-03',
              },
              {
                name: 'Intellectual Property Subcommittee',
                code: 'SSJU26',
                parent_committee_id: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SSJU/subcommittees/SSJU26.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 7,
                begin_date: '',
                end_date: '2021-01-03',
              },
              {
                name: 'Constitution Subcommittee',
                code: 'SSJU21',
                parent_committee_id: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/senate/committees/SSJU/subcommittees/SSJU21.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 5,
                begin_date: '',
                end_date: '2021-01-03',
              },
            ],
          },
          {
            congress: '115',
            chamber: 'Senate',
            title: 'Senator, 3rd Class',
            short_title: 'Sen.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: 'S6CA00584',
            seniority: '1',
            senate_class: '3',
            state_rank: 'junior',
            lis_id: 'S387',
            ocd_id: 'ocd-division/country:us/state:ca',
            start_date: '2017-01-03',
            end_date: '2019-01-03',
            office: '112 Hart Senate Office Building',
            phone: '202-224-3553',
            fax: null,
            contact_form:
              'https://www.harris.senate.gov/content/contact-senator',
            bills_sponsored: 52,
            bills_cosponsored: 396,
            missed_votes_pct: 0.33,
            votes_with_party_pct: 84.25,
            committees: [
              {
                name: 'Select Committee on Intelligence',
                code: 'SLIN',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SLIN.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 7,
                begin_date: '2017-01-03',
                end_date: '2019-01-03',
              },
              {
                name: 'Committee on the Budget',
                code: 'SSBU',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSBU.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 11,
                begin_date: '2017-01-03',
                end_date: '2019-01-03',
              },
              {
                name: 'Committee on Environment and Public Works',
                code: 'SSEV',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSEV.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 10,
                begin_date: '2017-01-03',
                end_date: '2019-01-03',
              },
              {
                name: 'Committee on Homeland Security and Governmental Affairs',
                code: 'SSGA',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSGA.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 7,
                begin_date: '2017-01-03',
                end_date: '2019-01-03',
              },
              {
                name: 'Committee on the Judiciary',
                code: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSJU.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: null,
                begin_date: '',
                end_date: '2019-01-03',
              },
            ],
            subcommittees: [
              {
                name: 'Regulatory Affairs and Federal Management Subcommittee',
                code: 'SSGA19',
                parent_committee_id: 'SSGA',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSGA/subcommittees/SSGA19.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 4,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name:
                  'Oversight, Agency Action, Federal Rights and Federal Courts',
                code: 'SSJU25',
                parent_committee_id: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSJU/subcommittees/SSJU25.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 7,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name: 'Privacy, Technology and the Law',
                code: 'SSJU23',
                parent_committee_id: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSJU/subcommittees/SSJU23.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 6,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name: 'Superfund, Waste Management, and Regulatory Oversight',
                code: 'SSEV09',
                parent_committee_id: 'SSEV',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSEV/subcommittees/SSEV09.json',
                side: 'minority',
                title: 'Ranking Member',
                rank_in_party: 1,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name: 'Constitution Subcommittee',
                code: 'SSJU21',
                parent_committee_id: 'SSJU',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSJU/subcommittees/SSJU21.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 5,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name: 'Transportation and Infrastructure',
                code: 'SSEV08',
                parent_committee_id: 'SSEV',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSEV/subcommittees/SSEV08.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 8,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name: 'Federal Spending Oversight and Emergency Management',
                code: 'SSGA18',
                parent_committee_id: 'SSGA',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSGA/subcommittees/SSGA18.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 2,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name: 'Federal Spending Oversight and Emergency Management',
                code: 'SSGA18',
                parent_committee_id: 'SSGA',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/senate/committees/SSGA/subcommittees/SSGA18.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 3,
                begin_date: '',
                end_date: '2019-01-03',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    status: 'OK',
    copyright: 'Copyright (c) 2019 Pro Publica Inc. All Rights Reserved.',
    results: [
      {
        member_id: 'G000559',
        first_name: 'John',
        middle_name: null,
        last_name: 'Garamendi',
        suffix: null,
        date_of_birth: '1945-01-24',
        gender: 'M',
        url: 'https://garamendi.house.gov',
        times_topics_url:
          'http://topics.nytimes.com/top/reference/timestopics/people/g/john_garamendi/index.html',
        times_tag: 'Garamendi, John (Per)',
        govtrack_id: '412382',
        cspan_id: '18413',
        votesmart_id: '29664',
        icpsr_id: '20958',
        twitter_account: 'RepGaramendi',
        facebook_account: 'repgaramendi',
        youtube_account: 'garamendiCA10',
        crp_id: 'N00030856',
        google_entity_id: '/m/05fvls',
        rss_url: 'https://garamendi.house.gov/rss.xml',
        in_office: true,
        current_party: 'D',
        most_recent_vote: '2019-07-25',
        last_updated: '2019-08-15 10:00:23 -0400',
        roles: [
          {
            congress: '116',
            chamber: 'House',
            title: 'Representative',
            short_title: 'Rep.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: 'H0CA10149',
            seniority: '12',
            district: '3',
            at_large: false,
            ocd_id: 'ocd-division/country:us/state:ca/cd:3',
            start_date: '2019-01-03',
            end_date: '2021-01-03',
            office: '2368 Rayburn House Office Building',
            phone: '202-225-1880',
            fax: null,
            contact_form: null,
            bills_sponsored: 19,
            bills_cosponsored: 309,
            missed_votes_pct: 1.57,
            votes_with_party_pct: 98.6,
            committees: [
              {
                name: 'Committee on Armed Services',
                code: 'HSAS',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/house/committees/HSAS.json',
                side: 'majority',
                title: 'Member',
                rank_in_party: 7,
                begin_date: '2019-01-15',
                end_date: '2021-01-03',
              },
              {
                name: 'Committee on Transportation and Infrastructure',
                code: 'HSPW',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/house/committees/HSPW.json',
                side: 'majority',
                title: 'Member',
                rank_in_party: 10,
                begin_date: '2017-01-17',
                end_date: '2021-01-03',
              },
            ],
            subcommittees: [
              {
                name: 'Strategic Forces',
                code: 'HSAS29',
                parent_committee_id: 'HSAS',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/house/committees/HSAS/subcommittees/HSAS29.json',
                side: 'majority',
                title: 'Member',
                rank_in_party: 4,
                begin_date: '2019-01-23',
                end_date: '2021-01-03',
              },
              {
                name: 'Readiness',
                code: 'HSAS03',
                parent_committee_id: 'HSAS',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/house/committees/HSAS/subcommittees/HSAS03.json',
                side: 'majority',
                title: 'Chair',
                rank_in_party: 1,
                begin_date: '2019-01-23',
                end_date: '2021-01-03',
              },
              {
                name: 'Coast Guard and Maritime Transportation',
                code: 'HSPW07',
                parent_committee_id: 'HSPW',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/house/committees/HSPW/subcommittees/HSPW07.json',
                side: 'majority',
                title: 'Member',
                rank_in_party: 5,
                begin_date: '',
                end_date: '2021-01-03',
              },
              {
                name: 'Highways and Transit',
                code: 'HSPW12',
                parent_committee_id: 'HSPW',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/house/committees/HSPW/subcommittees/HSPW12.json',
                side: 'majority',
                title: 'Member',
                rank_in_party: 4,
                begin_date: '',
                end_date: '2021-01-03',
              },
              {
                name:
                  'Economic Development, Public Buildings, and Emergency Management',
                code: 'HSPW13',
                parent_committee_id: 'HSPW',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/house/committees/HSPW/subcommittees/HSPW13.json',
                side: 'majority',
                title: 'Member',
                rank_in_party: 6,
                begin_date: '',
                end_date: '2021-01-03',
              },
              {
                name: 'Water Resources and Environment',
                code: 'HSPW02',
                parent_committee_id: 'HSPW',
                api_uri:
                  'https://api.propublica.org/congress/v1/116/house/committees/HSPW/subcommittees/HSPW02.json',
                side: 'majority',
                title: 'Member',
                rank_in_party: 4,
                begin_date: '',
                end_date: '2021-01-03',
              },
            ],
          },
          {
            congress: '115',
            chamber: 'House',
            title: 'Representative',
            short_title: 'Rep.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: 'H0CA10149',
            seniority: '10',
            district: '3',
            at_large: false,
            ocd_id: 'ocd-division/country:us/state:ca/cd:3',
            start_date: '2017-01-03',
            end_date: '2019-01-03',
            office: '2438 Rayburn House Office Building',
            phone: '202-225-1880',
            fax: '202-225-5914',
            contact_form: null,
            bills_sponsored: 10,
            bills_cosponsored: 503,
            missed_votes_pct: 4.21,
            votes_with_party_pct: 93.43,
            committees: [
              {
                name: 'Committee on Armed Services',
                code: 'HSAS',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/house/committees/HSAS.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 10,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name: 'Committee on Transportation and Infrastructure',
                code: 'HSPW',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/house/committees/HSPW.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 11,
                begin_date: '',
                end_date: '2019-01-03',
              },
            ],
            subcommittees: [
              {
                name: 'Seapower and Projection Forces',
                code: 'HSAS28',
                parent_committee_id: 'HSAS',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/house/committees/HSAS/subcommittees/HSAS28.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 5,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name: 'Strategic Forces',
                code: 'HSAS29',
                parent_committee_id: 'HSAS',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/house/committees/HSAS/subcommittees/HSAS29.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 4,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name: 'Water Resources and Environment',
                code: 'HSPW02',
                parent_committee_id: 'HSPW',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/house/committees/HSPW/subcommittees/HSPW02.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 7,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name: 'Coast Guard and Maritime Transportation',
                code: 'HSPW07',
                parent_committee_id: 'HSPW',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/house/committees/HSPW/subcommittees/HSPW07.json',
                side: 'minority',
                title: 'Ranking Member',
                rank_in_party: 1,
                begin_date: '',
                end_date: '2019-01-03',
              },
              {
                name: 'Railroads, Pipelines, and Hazardous Materials',
                code: 'HSPW14',
                parent_committee_id: 'HSPW',
                api_uri:
                  'https://api.propublica.org/congress/v1/115/house/committees/HSPW/subcommittees/HSPW14.json',
                side: 'minority',
                title: 'Member',
                rank_in_party: 7,
                begin_date: '',
                end_date: '2019-01-03',
              },
            ],
          },
          {
            congress: '114',
            chamber: 'House',
            title: 'Representative',
            short_title: 'Rep.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: 'H0CA10149',
            seniority: '8',
            district: '3',
            at_large: false,
            ocd_id: 'ocd-division/country:us/state:ca/cd:3',
            start_date: '2015-01-06',
            end_date: '2017-01-03',
            office: null,
            phone: null,
            fax: null,
            contact_form: null,
            bills_sponsored: 13,
            bills_cosponsored: 326,
            missed_votes_pct: 4,
            votes_with_party_pct: 94.25,
            committees: [
              {
                name: 'Committee on Armed Services',
                code: 'HSAS',
                api_uri:
                  'https://api.propublica.org/congress/v1/114/house/committees/HSAS.json',
                rank_in_party: 11,
                begin_date: '',
                end_date: '2017-01-03',
              },
              {
                name: 'Committee on Transportation and Infrastructure',
                code: 'HSPW',
                api_uri:
                  'https://api.propublica.org/congress/v1/114/house/committees/HSPW.json',
                rank_in_party: 14,
                begin_date: '',
                end_date: '2017-01-03',
              },
            ],
            subcommittees: [],
          },
          {
            congress: '113',
            chamber: 'House',
            title: 'Representative',
            short_title: 'Rep.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: '',
            seniority: '6',
            district: '3',
            at_large: false,
            ocd_id: 'ocd-division/country:us/state:ca/cd:3',
            start_date: '2013-01-03',
            end_date: '2015-01-03',
            office: null,
            phone: null,
            fax: null,
            contact_form: null,
            bills_sponsored: 6,
            bills_cosponsored: 331,
            missed_votes_pct: 2.22,
            votes_with_party_pct: 89.7,
            committees: [
              {
                name: 'Committee on Agriculture',
                code: 'HSAG',
                api_uri:
                  'https://api.propublica.org/congress/v1/113/house/committees/HSAG.json',
                rank_in_party: 21,
                begin_date: '2013-02-13',
                end_date: '2015-01-03',
              },
              {
                name: 'Committee on Transportation and Infrastructure',
                code: 'HSPW',
                api_uri:
                  'https://api.propublica.org/congress/v1/113/house/committees/HSPW.json',
                rank_in_party: 18,
                begin_date: '2013-01-03',
                end_date: '2015-01-03',
              },
              {
                name: 'Committee on Armed Services',
                code: 'HSAS',
                api_uri:
                  'https://api.propublica.org/congress/v1/113/house/committees/HSAS.json',
                rank_in_party: 13,
                begin_date: '2013-01-03',
                end_date: '2015-01-03',
              },
            ],
            subcommittees: [],
          },
          {
            congress: '112',
            chamber: 'House',
            title: 'Representative',
            short_title: 'Rep.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: '',
            seniority: '4',
            district: '10',
            at_large: false,
            ocd_id: 'ocd-division/country:us/state:ca/cd:10',
            start_date: '2011-01-04',
            end_date: '2013-01-03',
            office: null,
            phone: null,
            fax: null,
            contact_form: null,
            bills_sponsored: 14,
            bills_cosponsored: 235,
            missed_votes_pct: 4.79,
            votes_with_party_pct: 92,
            committees: [
              {
                name: 'Committee on Agriculture',
                code: 'HSAG',
                api_uri:
                  'https://api.propublica.org/congress/v1/112/house/committees/HSAG.json',
                rank_in_party: 20,
                begin_date: '2012-11-29',
                end_date: '2013-01-03',
              },
              {
                name: 'Committee on Armed Services',
                code: 'HSAS',
                api_uri:
                  'https://api.propublica.org/congress/v1/112/house/committees/HSAS.json',
                rank_in_party: 20,
                begin_date: '2011-01-19',
                end_date: '2013-01-03',
              },
              {
                name: 'Committee on Natural Resources',
                code: 'HSII',
                api_uri:
                  'https://api.propublica.org/congress/v1/112/house/committees/HSII.json',
                rank_in_party: 20,
                begin_date: '2011-01-19',
                end_date: '2012-11-29',
              },
            ],
            subcommittees: [],
          },
          {
            congress: '111',
            chamber: 'House',
            title: 'Representative',
            short_title: 'Rep.',
            state: 'CA',
            party: 'D',
            leadership_role: null,
            fec_candidate_id: '',
            seniority: '2',
            district: '10',
            at_large: false,
            ocd_id: 'ocd-division/country:us/state:ca/cd:10',
            start_date: '2009-11-05',
            end_date: '2011-01-03',
            office: null,
            phone: null,
            fax: null,
            contact_form: null,
            bills_sponsored: 8,
            bills_cosponsored: 259,
            missed_votes_pct: 7.41,
            votes_with_party_pct: 97.42,
            committees: [
              {
                name: 'Committee on Armed Services',
                code: 'HSAS',
                api_uri:
                  'https://api.propublica.org/congress/v1/111/house/committees/HSAS.json',
                rank_in_party: 36,
                begin_date: '2010-05-06',
                end_date: '2011-01-04',
              },
              {
                name: 'Committee on Science, Space, and Technology',
                code: 'HSSY',
                api_uri:
                  'https://api.propublica.org/congress/v1/111/house/committees/HSSY.json',
                rank_in_party: 15,
                begin_date: '2009-11-19',
                end_date: '2011-01-04',
              },
              {
                name: 'Committee on Transportation and Infrastructure',
                code: 'HSPW',
                api_uri:
                  'https://api.propublica.org/congress/v1/111/house/committees/HSPW.json',
                rank_in_party: 44,
                begin_date: '2009-11-19',
                end_date: '2011-01-04',
              },
            ],
            subcommittees: [],
          },
        ],
      },
    ],
  },
];
